name: build
on:
  push:
    branches: [master]
  pull_request:

jobs:
  tox:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        toxenv:
          - py37
          - py38
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox==3.26.0
      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}
